const fs=require('fs'), vm=require('vm'); const s=fs.readFileSync(__dirname+'/app.js','utf8');
function extract(name){let k=s.indexOf('const '+name+'='); if(k<0) throw Error('missing '+name); let st=s.indexOf('[',k), d=0,q=null,esc=false; for(let i=st;i<s.length;i++){let c=s[i]; if(q){if(esc)esc=false;else if(c==='\\')esc=true;else if(c===q)q=null;continue} if(c==='"'||c==="'"||c==='`'){q=c;continue} if(c==='[')d++; else if(c===']'&&--d===0)return vm.runInNewContext('('+s.slice(st,i+1)+')')} throw Error('unclosed '+name)}
let report=[],fail=[]; function ok(n,v,detail=''){report.push([n,!!v,detail]);if(!v)fail.push(n)}
for(let m=1;m<=10;m++){let a=extract('module'+m+'Questions');ok('CP module '+m+' has 10 questions',a.length===10,'count='+a.length);a.forEach((q,i)=>{ok(`CP M${m} Q${i+1} 4 choices`,q[1]?.length===4);ok(`CP M${m} Q${i+1} answer valid`,Number.isInteger(q[2])&&q[2]>=0&&q[2]<4);ok(`CP M${m} Q${i+1} explanation`,typeof q[3]==='string'&&q[3].length>15)})}
for(let prefix of ['ACA','AEL'])for(let n=101;n<=110;n++){let a=extract(prefix+n+'_QUESTIONS');ok(`${prefix}-${n} has 10 questions`,a.length===10,'count='+a.length);a.forEach((q,i)=>{ok(`${prefix}-${n} Q${i+1} 4 choices`,q.a?.length===4);ok(`${prefix}-${n} Q${i+1} answer valid`,Number.isInteger(q.c)&&q.c>=0&&q.c<4)})}
let ex=extract('AEL_EXEC_QUESTIONS');ok('AIM-EL executive exam has 50 questions',ex.length===50,'count='+ex.length);ex.forEach((q,i)=>{ok(`EL Exam Q${i+1} choices`,q.a?.length===4);ok(`EL Exam Q${i+1} answer`,Number.isInteger(q.c)&&q.c>=0&&q.c<4)});
let cb=extract('certificationQuestionBank');ok('AIM-CP final bank has 150 questions',cb.length===150,'count='+cb.length);for(let m=1;m<=10;m++)ok('CP final bank module '+m+' has 15',cb.filter(q=>q.module===m).length===15,'count='+cb.filter(q=>q.module===m).length);cb.forEach((q,i)=>{ok(`CP Bank Q${i+1} choices`,q.choices?.length===4);ok(`CP Bank Q${i+1} answer`,Number.isInteger(q.correct)&&q.correct>=0&&q.correct<4)});
// semantic consistency checks
ok('AAI maximum denominator 55 present',s.includes('33 ÷ 55')||s.includes('/55')||s.includes('55'));ok('A/G/H/X terminology present',/Autonomous/.test(s)&&/Gated/.test(s)&&/Human Reserved/.test(s)&&/Prohibited/.test(s));ok('Last Command external revocation present',/External Revocation/.test(s)||/external revocation/.test(s));ok('EL obsolete future alert absent',!s.includes('AIM-EL™ Enterprise Leader is a future certification path.'));ok('CA catalog ACA-108 corrected',s.includes('ACA-108","Last Command & Sovereign Control Architecture'));ok('CA catalog ACA-109 corrected',s.includes('ACA-109","High-Consequence & Physical Autonomy Architecture'));
console.log(JSON.stringify({checks:report.length,failed:fail.length,failures:fail},null,2)); process.exit(fail.length?1:0)
